{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-play-services",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.11.0.jar",
          "url": "kotlinx-coroutines-play-services-1.11.0.jar",
          "size": 10705,
          "sha512": "de7979c559364967e1c1fc261a63d62a6519adfe2b9f3892c3aa7e357a841473b9fdeeadab250f44d5df97a7133ceb11a9fd8b8001cc3ac51d490394806b697f",
          "sha256": "f441579409a9befc7391ae5620de773590dd6536b979d4a5a2a6e05b5f81e4d4",
          "sha1": "1669ebaddbc4df1c7cfff7ae983cd14d73579c11",
          "md5": "c1601113aefa864a543d20ecce6bbf4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.11.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.11.0.jar",
          "url": "kotlinx-coroutines-play-services-1.11.0.jar",
          "size": 10705,
          "sha512": "de7979c559364967e1c1fc261a63d62a6519adfe2b9f3892c3aa7e357a841473b9fdeeadab250f44d5df97a7133ceb11a9fd8b8001cc3ac51d490394806b697f",
          "sha256": "f441579409a9befc7391ae5620de773590dd6536b979d4a5a2a6e05b5f81e4d4",
          "sha1": "1669ebaddbc4df1c7cfff7ae983cd14d73579c11",
          "md5": "c1601113aefa864a543d20ecce6bbf4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.11.0-sources.jar",
          "url": "kotlinx-coroutines-play-services-1.11.0-sources.jar",
          "size": 1868,
          "sha512": "baaf0a45131326e2408899d92f236d0307a0e560366e8933d66712e0e852ac2c3b04cf014db2cdc5a05c1975026b0f6f2bbc87f369e960e4d92358c62730e9ee",
          "sha256": "44f6b640fd2661c88b0155816501a4f5624ad366be74abcd0fc93515996223af",
          "sha1": "34cf6bab9bcd950c4cf16ac7360b1b9cc31c8610",
          "md5": "2aad57540563c16b3383bdd85acd6a60"
        }
      ]
    }
  ]
}
