{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14428372"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.10.0-sources.jar",
          "url": "lifecycle-service-2.10.0-sources.jar",
          "size": 6861,
          "sha512": "528f12c7868c9f066b30dd707ade5db7e0eb7fd58f759acdb94a9f98af32ab0c94fefc325d975c1312099669a16739470ffa2e01a0c520ded607c44de230d263",
          "sha256": "410a1cb6445741450582a7a4071537c87912780185eec763911d183b73384584",
          "sha1": "f1a86e9fba9a89a6e8bedb99797c57366f7b3e69",
          "md5": "a0983dfb6f4cc45b806bc2632d58b3de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.10.0.aar",
          "url": "lifecycle-service-2.10.0.aar",
          "size": 9951,
          "sha512": "cf61ed8aee2d45f2d099cf85bbd13b11ada0b59ee78b6a74c6c921085a4f7094d5abdd5b9d2716838302f2746f56a0094d16be5dcf4f8a8c3f73ac1b7fe61739",
          "sha256": "60bea13bbea42b6aa007e5a48c0b432c9b3dd05887482a43baa8f5a9042dc2e2",
          "sha1": "dd03a4f7c84bfd29291d1c26313bd8623ef9817d",
          "md5": "733dea8d27882d7d4fb27a949f3ad435"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.10.0.aar",
          "url": "lifecycle-service-2.10.0.aar",
          "size": 9951,
          "sha512": "cf61ed8aee2d45f2d099cf85bbd13b11ada0b59ee78b6a74c6c921085a4f7094d5abdd5b9d2716838302f2746f56a0094d16be5dcf4f8a8c3f73ac1b7fe61739",
          "sha256": "60bea13bbea42b6aa007e5a48c0b432c9b3dd05887482a43baa8f5a9042dc2e2",
          "sha1": "dd03a4f7c84bfd29291d1c26313bd8623ef9817d",
          "md5": "733dea8d27882d7d4fb27a949f3ad435"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0"
          },
          "reason": "lifecycle-service is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.10.0-versionMetadata.json",
          "url": "lifecycle-service-2.10.0-versionMetadata.json",
          "size": 789,
          "sha512": "70183a035bc4c31edb905625b219b2c47b6969c8b5b39099539742a46a032f6035b06700f4770a2eb245244f58ea57ed9080c693806683ce04bc65b1519760f1",
          "sha256": "a1ca4cf4beae5b39e1bd5e6017cf605c720b7c6e3fa1704d0db890eed2af55a1",
          "sha1": "0a1b77d92e12b40e00f89dd3035ec9699ffb4ba9",
          "md5": "99f62641a56d7bb7f77673a5ac447356"
        }
      ]
    }
  ]
}